### ISSUE TITLE
Przesyłanie wiadomości UTF8

### ISSUE THREAD

**Issue by kliput** [kliput/peanotes#2]
Przesyłanie wiadomości UTF8.

**Comment by kliput** [comment]
GUI dodaje wiadomości unicode() - później jest wewnętrzny błąd SPADE. Może trzeba robić z jednej strony .encode(...) a później .decode(...)?

Traceback (most recent call last):
  File "/home/kliput/Programowanie/agenty/projekt/peanotes/gui.py", line 197, in sendMessage
    self.mainGui.client.addMsg(self.**message**)
  File "/home/kliput/Programowanie/agenty/projekt/peanotes/core_mock.py", line 91, in addMsg
    self.agent.sendMsg(message)
  File "/home/kliput/Programowanie/agenty/projekt/peanotes/client_agent.py", line 31, in sendMsg
    self._sendMsg(message, new_msg_to_server_ontology)
  File "/home/kliput/Programowanie/agenty/projekt/peanotes/client_agent.py", line 44, in _sendMsg
    self.send(msg)
  File "/usr/local/lib/python2.7/dist-packages/SPADE-2.2-py2.7.egg/spade/Agent.py", line 793, in send
    self._sendTo(ACLmsg, ACLmsg.getReceivers(), method=method.strip())
  File "/usr/local/lib/python2.7/dist-packages/SPADE-2.2-py2.7.egg/spade/Agent.py", line 887, in _sendTo
    jabber_msg.setBody(ACLmsg.getContent())
  File "/usr/local/lib/python2.7/dist-packages/SPADE-2.2-py2.7.egg/xmpp/protocol.py", line 393, in setBody
    self.setTagData('body',val)
  File "/usr/local/lib/python2.7/dist-packages/SPADE-2.2-py2.7.egg/xmpp/simplexml.py", line 228, in setTagData
    except: self.addChild(tag,attrs,payload=[ustr(val)])
  File "/usr/local/lib/python2.7/dist-packages/SPADE-2.2-py2.7.egg/xmpp/simplexml.py", line 32, in ustr
    if type(r)<>type(u''): return unicode(r,ENCODING)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf3 in position 230: invalid continuation byte

**Comment by berespt** [comment]
Naprawione, teraz message.content podczas serializowania (serializer.serialize()) i deserializowania (serializer.deserialize()) jest kodowane i dekodowane
